### ISSUE TITLE
Could not resolve com.github.armcha:AutoLinkTextViewV2:3.0.0.

### ISSUE THREAD

**Issue by marcobaldo** [armcha/AutoLinkTextViewV2#14]
Seems like the package disappeared from the repos. Any ideas?

```gradle
> Could not resolve all files for configuration ':app:devDebugRuntimeClasspath'.
   > Could not find com.github.armcha:AutoLinkTextViewV2:3.0.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/armcha/AutoLinkTextViewV2/3.0.0/AutoLinkTextViewV2-3.0.0.pom
       - https://jcenter.bintray.com/com/github/armcha/AutoLinkTextViewV2/3.0.0/AutoLinkTextViewV2-3.0.0.pom
       - https://repo.maven.apache.org/maven2/com/github/armcha/AutoLinkTextViewV2/3.0.0/AutoLinkTextViewV2-3.0.0.pom
       - https://jitpack.io/com/github/armcha/AutoLinkTextViewV2/3.0.0/AutoLinkTextViewV2-3.0.0.pom
```

**Comment by armcha** [comment]
Fixed.
Thanks for the issue!

**Comment by balwinderSingh1989** [comment]
@armcha  in which version this got fixed ?

Still getting the same

   > Could not find com.github.armcha:AutoLinkTextViewV2:3.0.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/armcha/AutoLinkTextViewV2/3.0.0/AutoLinkTextViewV2-3.0.0.pom
       - https://repo.maven.apache.org/maven2/com/github/armcha/AutoLinkTextViewV2/3.0.0/AutoLinkTextViewV2-3.0.0.pom
       - https://jitpack.io/com/github/armcha/AutoLinkTextViewV2/3.0.0/AutoLinkTextViewV2-3.0.0.pom
     Required by:
